version: '3.8'

services:
  api:
    build: '.'
    depends_on:
      - postgres
    ports:
      - '8000:8000'
    command: gunicorn -w 1 -k uvicorn.workers.UvicornWorker applications.rest.main:app -b 0.0.0.0:8000 --disable-redirect-access-to-syslog

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - blog-postgres:/data
    environment:
        POSTGRES_INITDB_ROOT_USERNAME: 'developer'
        POSTGRES_INITDB_ROOT_PASSWORD: 'nWGfhU5rHBaRtDfGl7RO3wIp7LD82aoOSJx0NlfuCI'
        POSTGRES_INITDB_DATABASE: 'blog'

volumes:
  blog-postgres:
