version: '3.8'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    hostname: database_blog
    environment:
      - POSTGRES_USER=fastapi_blog
      - POSTGRES_PASSWORD=fastapi_blog
      - POSTGRES_DB=fastapi_blog

  web:
    build:
      dockerfile: Dockerfile
    command: uvicorn src.blog.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - /media:/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db


volumes:
  postgres_data: